<?xml version="1.0"?>
<package format="3">
  <name>jsk_visualization</name>
  <version>2.1.10</version>
  <description>Metapackage that contains visualization package for jsk-ros-pkg</description>

  <maintainer email="ueda@jsk.t.u-tokyo.ac.jp">Ryohei Ueda</maintainer>
  <author email="ueda@jsk.t.u-tokyo.ac.jp">Ryohei Ueda</author>
  <author email="k-okada@jsk.t.u-tokyo.ac.jp">Kei Okada</author>
  <author email="youhei@jsk.imi.i.u-tokyo.ac.jp">Youhei Kakiuchi</author>
  <author email="obinata@jsk.imi.i.u-tokyo.ac.jp">Yoshiki Obinata</author>

  <license>BSD</license>
  <url type="website">http://ros.org/wiki/jsk_visualization</url>
  <url type="repository">https://github.com/jsk-ros-pkg/jsk_visualization</url>
  <url type="bugtracker">https://github.com/jsk-ros-pkg/jsk_visualization/issues</url>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>jsk_rqt_plugins</exec_depend>
  <exec_depend>jsk_rviz_plugins</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
