on:
  push:
    branches:
      - ros2
  pull_request:

jobs:
  ros2:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-latest
            ros_distro: jazzy
          - runner: ubuntu-24.04-arm
            ros_distro: jazzy
          - runner: ubuntu-latest
            ros_distro: lyrical
          - runner: ubuntu-24.04-arm
            ros_distro: lyrical
          - runner: ubuntu-latest
            ros_distro: rolling
          - runner: ubuntu-24.04-arm
            ros_distro: rolling
    steps:
      - uses: actions/checkout@v7
      - uses: ros-industrial/industrial_ci@master
        env:
          ROS_DISTRO: ${{ matrix.ros_distro }}
